### PR TITLE
Add support for noItemsText in Dropdown

### PR DESCRIPTION
**Pull request by mosch**
New Feature:
- Dropdown: New prop "noItemsText" allows you to show a unselectable text if no items are available to choose.

Screenshot 2019-07-12 at 10 07 32

Checklist:

- [x] Test added / Snapshots updated
- [x] Documentation added / updated

### CODE REVIEW

**Comment by fivenp** [comment]
hmmmm...... this is a little paradox :)

why would a user be able click on a dropdown at all if it has no items?

if this is intended to be the groundwork for a filterable dropdown it makes of course sense in that context :)

**Comment by mosch** [comment]
> why would a user be able to click on a dropdown at all if it has no items?

We have the situation where do should choose something for complete the form – but there is nothing you can choose from for some reason. What would you suggest as a solution?

**Comment by janrembold** [comment]
@mosch I don't know the exact use-case but showing a simple text or even better show nothing at all sounds much better than adding a dropdown that tells the user "it was useless that you click me". What I mean is that a Dropdown forces the user to make a click just to inform her that there is nothing to choose. So I would propose to completely hide it -> KISS

**Comment by mosch** [comment]
Ok ☹️

**Pull request closed without merging**
