### PR TITLE
Switch to cross-fetch 🐍?

### PR DESCRIPTION
**Pull request by yamafaktory**
Checklist:

- [ ] Test added / Snapshots updated
- [ ] Documentation added / updated

This PR could be - eventually - used as an upgrade to #137 ...

### CODE REVIEW

**Comment by yamafaktory** [comment]
@adieuadieu:

- App https://github.com/allthings/app/pull/1375
- Cockpit https://github.com/allthings/cockpit/pull/752

Now everything should be aligned (#137).

**Comment by yamafaktory** [comment]
Double approval === rejection ^^ ?

**Comment by adieuadieu** [comment]
Neat.

**Comment by dan-lee** [comment]
@yamafaktory See https://github.com/allthings/elements/pull/139/commits/62585e0de1e2585ae5e647eb8b4403b0c6fb1ea3 and https://github.com/jefflau/jest-fetch-mock/issues/51#issuecomment-365763980 🤷‍♀️

**Pull request merged**
