### PR TITLE
Customise Colors for Calendar

### LINKED ISSUE #602: Color for Calendar
The `Calendar` Component has it's active day color currently hardcoded - we should switch over to make it "dynamic"

### PR DESCRIPTION
**Pull request by fivenp**
This was intended to fix #602 one day - sadly it doesn't work that "easy"....

So for now - I just changed the disabled styling (otherwise it's hard to distinguish between disabled in the past and dates overlapping to the next month for example) and added ColorPalette colors which brigthen/darken accordingly :/

**Before**:
image

**After**:
image

Checklist:

- [ ] Test added / Snapshots updated
- [ ] Documentation added / updated

### CODE REVIEW

**Comment by mosch** [comment]
🤷🏼‍♂️

**Comment by fivenp** [comment]
yeah.... I need to find some time to continue working on it :/

**Comment by dan-lee** [comment]
Cool! I like the gradient pattern 🌈. But it looks a little bit weird when it's chopped off because the tiles end, doesn't it? I don't know if there's a good solution for that.

**Comment by fivenp** [comment]
> Cool! I like the gradient pattern 🌈. But it looks a little bit weird when it's chopped off because the tiles end, doesn't it? I don't know if there's a good solution for that.

Fully agree... maybe we add a margin between the cells in future? :)

**Pull request merged**
