### PR TITLE
added extra padding on the text input field, so the checkmark doesnt …

### PR DESCRIPTION
**Pull request by iamn1ck**
…overlap over the text

Checklist:

- [ ] Test added / Snapshots updated
- [ ] Documentation added / updated

### CODE REVIEW

**Comment by fivenp** [comment]
uhm wait - this will „break“ all our forms!

**Comment by dan-lee** [comment]
[You can see it very clearly here in storybook](https://deploy-preview-667--allthings-elements.netlify.com/?selectedKind=Forms&selectedStory=SimpleForm&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

This would break a lot of form layouts, what do you want to achieve? Please be more descriptive in your PR.

**Comment by fivenp** [comment]
As daniel said - what's the expected result?

Is it maybe to bring checkbox and form input labels/placeholders to be "in line"?
image

**Comment by iamn1ck** [comment]
This is before, and you can see the checkmark covers the text at the end
screenshot_2019-02-25 storybook 1

This is the after
screenshot_2019-02-25 storybook

**Comment by fivenp** [comment]
well - in this case a single paddingRight: 35 will do the trick (otherwise it also affects the left one which is off...) - but:

* Only if the input really uses the checkmark

**Comment by fivenp** [comment]
fixed by #811

**Pull request closed without merging**
