### PR TITLE
Fix/button background color

### PR DESCRIPTION
**Pull request by fivenp**
I just realised `kewler` will break all our hero images / buttons where we pass `rgba()` or apparently even `rgb()` values with the last button update (PR #583)

Which makes partially sense... Since you cannot lighten/darken a transparent color (u basically can... but kewler can't :))

Soooo this is a hot fix to NOT break current implementations - it checks whether we pass a `rgb(a)` value (therefor no hover effect is added)

Checklist:

- [x] Test added / Snapshots updated
- [ ] Documentation added / updated

### CODE REVIEW

**Comment by dan-lee** [comment]
I think we should rather check for hex or non-hex, because there is not only `rgb/rgba` but also `hsl/hsla` and the whole HTML color palette.

**Comment by fivenp** [comment]
> I think we should rather check for hex or non-hex, because there is not only `rgb/rgba` but also `hsl/hsla` and the whole HTML color palette.

You're totally right... Great point! My dream scenario is to also add `hsl()` and `rgb()` to `hex` conversions (no `hsla` and `rgba`) one day

**Comment by dan-lee** [comment]
Cool! Btw: [No `includes` in IE](https://caniuse.com/#feat=es6-string-includes) 😕

**Comment by fivenp** [comment]
> Cool! Btw: [No `includes` in IE](https://caniuse.com/#feat=es6-string-includes) 😕

Life is beautiful..... :)

**Pull request merged**
