### PR TITLE
Add spacing helper

### PR DESCRIPTION
**Pull request by dan-lee**
Does this make sense to add?

Example usage:

```jsx
function App() {
  return (
    <div
      {...spacing.inner({ vertical: 30 })}
      {...spacing.outer(15)}
    >
      Content
    </div>
  )
}
```

Checklist:

- [ ] Test added / Snapshots updated
- [ ] Documentation added / updated

### CODE REVIEW

**Comment by mosch** [comment]
Great idea! Maybe it's worth thinking it spacing steps like `1px 3px 5px 10px 15px`?

**Comment by fivenp** [comment]
> Great idea! Maybe it's worth thinking it spacing steps like `1px 3px 5px 10px 15px`?

being more verbose makes sense somehow.... we usually use 5px steps for margins/paddings (at least in 90% of the use cases) - maybe something like this? 

```
{
  "s" => 5,
  "m" => 10,
  "l" => 15,
  "xl" => 20,
}
```

**Comment by dan-lee** [comment]
I think it would be sensible to provide these as defaults.

Like:
```
export const SPACING = {
  s: 5,
  m: 10,
  l: 15,
  xl: 20,
}
```

**Comment by fivenp** [comment]
👑 !

**Pull request closed without merging**
