### PR TITLE
chore: removing 'import * as React' and const x: React.FC<Prop>

### PR DESCRIPTION
**Pull request by xeoxx**
In accordance to # 11 and # 20 of the following:
https://medium.com/@martin_hotell/10-typescript-pro-tips-patterns-with-or-without-react-5799488d6680#78b9

This changes:
1. `import * as React from 'react'` to `import React from 'react'`
2. `const x: React.FC<IXProps> = (props)=>...` to `const x = (props: IXProps)=>...`

Checklist:

- [x] Test added / Snapshots updated
- [x] Documentation added / updated

### CODE REVIEW

**Comment by mosch** [comment]
👏🏼

**Comment by dan-lee** [comment]
So are all `children` now type `any`?

**Comment by mosch** [comment]
> So are all `children` now type `any`?

I thought the same during my review, however I'd expected the linting to complain about _implicit any_.

**Comment by xeoxx** [comment]
> children

They most of the time inherit from `IViewProps` or are declared by `React.PropsWithChildren<IMyProps>`.
Unless defined otherwise they are of type `React.ReactNode`.
This is the same as when they would use `const x: React.FC<IMyProps> = ...`

**Comment by dan-lee** [comment]
Generally I like the PR, but as you said now we're basically using `PropsWithChildren`, which doesn't really make a difference.
The article states that one should explicitly type their children.

**Comment by xeoxx** [comment]
> Generally I like the PR, but as you said now we're basically using `PropsWithChildren`, which doesn't really make a difference.
> The article states that one should explicitly type their children.
Yap, but maybe not in this PR?

**Pull request merged**
