### PR TITLE
EditableText

### PR DESCRIPTION
**Pull request by yamafaktory**
Live test: https://deploy-preview-348--allthings-elements.netlify.com/?selectedKind=Animations&selectedStory=HorizontalView&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Checklist:

- [x] Test added / Snapshots updated
- [x] Documentation added / updated

### CODE REVIEW

**Comment by yamafaktory** [comment]
We got a lot of great & valuable feedback during the UIX workshop, let's try to gather all those in here:

- Styling concerns, how to keep the component UI obvious for the user without making it bloated? Possible solutions: dropping the default icon (should still be possible to display it, we need a way to deliver hints / warning / etc), no decoration, etc.

- Focus when clicking on the icon (id we keep it displayed upfront...).

Please write down what come to your mind (@dan-lee @fivenp @hasznosl @kialysa @monsterlie @mosch), the only thing to keep in mind (IMHO) is that any kind of styling applied to this component should not interfere with it (i.e. this just a simple Text component under the hood, so you can change... a lot of things 😄).

**Comment by fivenp** [comment]
I'd only do "focus on icon click" for now - see how it behaves later on - and fix/extend it if we realise it's not behaving like we want 😄 

Everything else -> 🚀 
Great job!

**Comment by yamafaktory** [comment]
@fivenp Thanks a lot for the feedback, I'll add that behavior & ping you back!

**Comment by monsterlie** [comment]
I really like it! Think we can approve it over time, when we have more usecases for it and see what else is needed. For now I would go like it is! 👍

**Comment by yamafaktory** [comment]
Should we go ahead with this PR and get it merged (cc/ @kialysa + @dan-lee) 🧟‍♀️?

**Comment by yamafaktory** [comment]
@kialysa + @dan-lee 🏓: Drop it or keep it 😄?

**Comment by kialysa** [comment]
keep!!! 🙆‍♀️

**Comment by mosch** [comment]
Great, can we update to resolve conflicts?

**Comment by yamafaktory** [comment]
Sure will do 🚀

**Pull request merged**
